### ISSUE TITLE
Feature Request: config/variables for units

### ISSUE THREAD

**Issue by ReevesL** [BasvanH/habpanel-widget-weatherunderground#2]
Thank you for the plugin, very nicely done.

I'm manually editing the units in the HTML from °C to °F so I know it's not 47°C out ;). It would be a nice feature to specify units in a config or as a set of variables at the top of the code.

**Comment by BasvanH** [comment]
Thank you!

You can set the SourceUnit in the Weather Underground Thing, please see the [documentation](https://docs.openhab.org/addons/bindings/weatherunderground/readme.html). If you have configured your Thing thru PaperUi, you can edit the /userdata/jsondb/org.eclipse.smarthome.core.thing.Thing.json file.
