### ISSUE TITLE
Other weather provider?

### ISSUE THREAD

**Issue by Metal-Frog** [BasvanH/habpanel-widget-weatherunderground#3]
Hi,
Weather Underground isn't free anymore.
Is it possible to use another provider?

Greetz, Tom

**Comment by BasvanH** [comment]
I will Investigate.

**Comment by BasvanH** [comment]
Which OH binding would you suggest to use with the Weather Widget?

**Comment by Metal-Frog** [comment]
>Which OH binding

I won't care - whatever works :)

**Comment by viktor-sc** [comment]
Hey,
Yeah, it would be really cool if it would work with other services, too.
I guess the iconkey is the hard part, right?

**Comment by BasvanH** [comment]
I'm currently working on a widget that works with the [OpenWeatherMap](https://www.openhab.org/addons/bindings/openweathermap/) binding.

**Comment by BasvanH** [comment]
I've created a new widget to support OpenWeatherMap binding. It can be used with a free API key.

https://github.com/BasvanH/habpanel-widget-openweathermap
